
on: [push]
jobs:
  query-rapid-api-service:
    runs-on: ubuntu-latest
    steps:
        name: Test
        run: 
          echo = $open_api_key
        env:
          open_api_key: ${{ secrets.open_api_key }}
          
