
on: [push]
jobs:
  query-rapid-api-service:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install pip packages
        run: pip install requests
      - name: query rapidapi service
        run: python streamlit_app.py "$open_api_key" 
        env:
          open_api_key: ${{ secrets.open_api_key }}
          
